# Start from the official Python base image
FROM python:3.9

# The /app directory should act as the main application directory
WORKDIR /app

# copy requirements file to new directory
COPY ./requirements.txt /app/requirements.txt

# Install packages, --no-cache-dir tells computer to redownload packages every restart
RUN pip install --upgrade -r /app/requirements.txt

# copy backend into docker image
COPY . /app

# run app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]